- hosts: all
  sudo: yes
  roles:
    - aleiphoenix.ubuntu-common
  tags:
    - base

- hosts: all
  sudo: yes
  roles:
    - franklinkim.users
  vars:
    users:
      - username: mss
        name: mss
        authorized_keys: []
    users_group: mss
  tags:
    - base

- hosts: all
  sudo: yes
  remote_user: mss
  roles:
    - mss_environment
  tags:
    - mss
