---
# tasks file for mss_environment

- name: add anjuke-ubuntu
  apt_repository: repo='deb http://10.10.3.224/ubuntu-anjuke/ precise  main multiverse restricted universe'
                  state=present

- name: make directory for mss
  file: dest={{ mss_home }}/{{ item }}
        owner=mss
        group=mss
        state=directory
  with_items:
    - bin
    - apps
    - pids
    - logs
    - template

- name: prepare shell scripts
  copy: src={{ inventory_dir }}/../bin/
        dest={{ mss_home }}/bin
        owner=mss
        group=mss

- name: prepare configuration template
  copy: src={{ inventory_dir }}/../conf/
        dest={{ mss_home }}/template
        owner=mss
        group=mss

- name: install packages
  apt: pkg={{ item }}
       state=present
  with_items:
    - libzmq3
    - oracle-java8-jdk
  ignore_errors: yes

- name: prepare mss.jar if exists
  copy: src={{ inventory_dir }}/../target/mss-{{ mss_version }}.jar
        dest={{ mss_home }}/bin
        owner=mss
        group=mss
  ignore_errors: yes
